import { database } from "react-icons-kit/feather";

const musics = [
  {
    id: 0,
    name: "Nice piano and ukulele",
    author: "Royalty",
    img: "https://cdn.notefolio.net/img/6d/72/6d726d99987bfe6eef13749b00437d70de0729b4e80164fc2b1fbf598d1030de_v1.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-buddy.mp3",
    duration: "2:02",
    genre: { genre_name: "Jazz" },
  },
  {
    id: 1,
    name: "Gentle acoustic",
    author: "Acoustic",
    img: "https://www.bensound.com/bensound-img/beyondtheline.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-beyondtheline.mp3",
    duration: "2:20",
    genre: { genre_name: "Rock" },
  },
  {
    id: 2,
    name: "Corporate motivational",
    author: "Corporate",
    img: "https://www.bensound.com/bensound-img/memories.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-memories.mp3",
    duration: "2:59",
    genre: { genre_name: "Cinematic" },
  },
  {
    id: 3,
    name: "Slow cinematic",
    author: "Royalty",
    img: "https://www.bensound.com/bensound-img/slowmotion.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-slowmotion.mp3",
    duration: "3:26",
    genre: { genre_name: "Rap" },
  },
  {
    id: 4,
    name: "CREEPY",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/creepy.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-creepy.mp3",
    duration: "3:26",
    genre: { genre_name: "ETC" },
  },
  {
    id: 5,
    name: "SCI-FI",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/scifi.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-scifi.mp3",
    duration: "3:26",
    genre: { genre_name: "Electronica" },
  },
  {
    id: 6,
    name: "MOOSE",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/moose.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-moose.mp3",
    duration: "3:26",
    genre: { genre_name: "Electronica" },
  },
  {
    id: 7,
    name: "E.R.F.",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/erf.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-erf.mp3",
    duration: "3:26",
    genre: { genre_name: "Electronica" },
  },
  {
    id: 8,
    name: "JAZZY FRENCHY",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/jazzyfrenchy.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-jazzyfrenchy.mp3",
    duration: "3:26",
    genre: { genre_name: "Jazz" },
  },
  {
    id: 9,
    name: "LOVE",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/love.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-love.mp3",
    duration: "3:26",
    genre: { genre_name: "Jazz" },
  },
  {
    id: 10,
    name: "DON'T FORGET",
    author: "Yari",
    img: "https://www.bensound.com/bensound-img/yari.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-dontforget.mp3",
    duration: "3:26",
    genre: { genre_name: "Jazz" },
  },
  {
    id: 11,
    name: "CHARLIE'S MOOD",
    author: "Ponymusic",
    img: "https://www.bensound.com/bensound-img/ponymusic.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-charliesmood.mp3",
    duration: "3:26",
    genre: { genre_name: "Jazz" },
  },
  {
    id: 12,
    name: "GOOD TOGETHER",
    author: "TwinsMusic",
    img: "https://www.bensound.com/bensound-img/twinsmusic.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-goodtogether.mp3",
    duration: "3:26",
    genre: { genre_name: "Acoustic" },
  },
  {
    id: 13,
    name: "BLUE FIELDS",
    author: "StereoChipz",
    img: "https://www.bensound.com/bensound-img/stereochipz2.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-bluefields.mp3",
    duration: "3:26",
    genre: { genre_name: "Acoustic" },
  },
  {
    id: 14,
    name: "ALONG THE RIVER",
    author: "Evert Zeevalkink",
    img: "https://www.bensound.com/bensound-img/evertzeevalkink.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-alongtheriver.mp3",
    duration: "3:26",
    genre: { genre_name: "Acoustic" },
  },
  {
    id: 15,
    name: "TENDERNESS",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/tenderness.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-tenderness.mp3",
    duration: "3:26",
    genre: { genre_name: "Acoustic" },
  },
  {
    id: 16,
    name: "NOVEMBER",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/november.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-november.mp3",
    duration: "3:26",
    genre: { genre_name: "Cinematic" },
  },
  {
    id: 17,
    name: "PIANO MOMENT",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/pianomoment.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-pianomoment.mp3",
    duration: "3:26",
    genre: { genre_name: "Cinematic" },
  },
  {
    id: 18,
    name: "TOMORROW",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/tomorrow.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-tomorrow.mp3",
    duration: "3:26",
    genre: { genre_name: "Cinematic" },
  },
  {
    id: 19,
    name: "BETTER DAYS",
    author: "Benjamin Tissot",
    img: "https://www.bensound.com/bensound-img/betterdays.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-betterdays.mp3",
    duration: "3:26",
    genre: { genre_name: "Cinematic" },
  },
];

export default musics;
