const musics = [
  {
    id: 1,
    name: "Nice piano and ukulele",
    author: "Royalty",
    img: "https://cdn.notefolio.net/img/6d/72/6d726d99987bfe6eef13749b00437d70de0729b4e80164fc2b1fbf598d1030de_v1.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-buddy.mp3",
    duration: "2:02",
    genre: { genre_name: "Jazz" },
  },
  {
    id: 2,
    name: "Gentle acoustic",
    author: "Acoustic",
    img: "https://www.bensound.com/bensound-img/beyondtheline.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-beyondtheline.mp3",
    duration: "2:20",
    genre: { genre_name: "Rock" },
  },
  {
    id: 3,
    name: "Corporate motivational",
    author: "Corporate",
    img: "https://www.bensound.com/bensound-img/memories.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-memories.mp3",
    duration: "2:59",
    genre: { genre_name: "Cinematic" },
  },
  {
    id: 4,
    name: "Slow cinematic",
    author: "Royalty",
    img: "https://www.bensound.com/bensound-img/slowmotion.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-slowmotion.mp3",
    duration: "3:26",
    genre: { genre_name: "Rap" },
  },
  {
    id: 5,
    name: "Slow cinematic",
    author: "Royalty",
    img: "https://www.bensound.com/bensound-img/slowmotion.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-slowmotion.mp3",
    duration: "3:26",
    genre: "BossaNova",
  },
  {
    id: 6,
    name: "THE JAZZ PIANO",
    author: "Benjamin Tissot ",
    img: "https://www.bensound.com/bensound-img/thejazzpiano.jpg",
    audio: "https://www.bensound.com/bensound-music/bensound-thejazzpiano.mp3",
    duration: "3:26",
    genre: { genre_name: "Fork" },
  },
];

export default musics;
