import {
  faAngry as farAngry,
  faFlushed as farFlushed,
  faGrimace as farGrimace,
  faDizzy as farDizzy,
  faMeh as farMeh,
  faFrown as farFrown,
  faSmile as farSmile,
  faGrinBeamSweat as farGrinBeamSweat,
  faGrinHearts as farGrinHearts,
  faTired as farTired,
  faSadTear as farSadTear,
  faSadCry as farSadCry,
  faMehRollingEyes as farMehRollingEyes,
  faGrinStars as farGrinStars,
  faSurprise as farSurprise,
  faLaughBeam as farLaughBeam,
  faKissWinkHeart as farKissWinkHeart,
  faLaughSquint as farLaughSquint,
  faGrinSquintTears as farGrinSquintTears,
  faGrinTongueWink as farGrinTongueWink,
} from "@fortawesome/free-regular-svg-icons";

export default [
  { id: 1, emoji: farMeh, color: "#a1a1a4" },
  { id: 2, emoji: farSmile, color: "#ffdb00" },
  { id: 3, emoji: farLaughBeam, color: "#fdca30" },
  { id: 4, emoji: farLaughSquint, color: "#ffcb00" },
  { id: 5, emoji: farGrinSquintTears, color: "#fdbb30" },
  {
    id: 6,
    emoji: farKissWinkHeart,
    color: "#ea4c89",
  },
  { id: 7, emoji: farGrinHearts, color: "#ea4c89" },
  { id: 8, emoji: farGrinStars, color: "#6b5aed" },
  { id: 9, emoji: farGrinTongueWink, color: "#2d72d9" },
  {
    id: 10,
    emoji: farGrinBeamSweat,
    color: "#7acef4",
  },
  { id: 11, emoji: farFrown, color: "#ff8200" },
  { id: 12, emoji: farAngry, color: "#fe423f" },
  { id: 13, emoji: farGrimace, color: "#e32119" },
  { id: 14, emoji: farTired, color: "#97a2a2" },
  { id: 15, emoji: farDizzy, color: "#8a8b8c" },
  { id: 16, emoji: farSurprise, color: "#8ee000" },
  { id: 17, emoji: farFlushed, color: "#6cc24a" },
  {
    id: 18,
    emoji: farMehRollingEyes,
    color: "#8a8acb",
  },
  { id: 19, emoji: farSadTear, color: "#2bb3f3" },
  { id: 20, emoji: farSadCry, color: "#147efb" },
];
